site:
  name: GoDev
  site: 'https://godev.biz.id'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: 'MVlakcTpdkCSsi5DUpjZ5PsdtqXA_QjQL70ueeU7Vlk'

# Default SEO metadata
metadata:
  title:
    default: GoDev
    template: '%s | GoDev'
  description: "Jasa Done-For-You Otomatisasi Google Workspace untuk UMKM Indonesia. Usaha jalan terus, pemilik bisa libur."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: GoDev
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@godev_id'
    site: '@godev_id'
    cardType: summary_large_image

i18n:
  language: id
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true
    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true
    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false
    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: 'G-G0NEG69QSL'
      
ui:
  theme: 'system'